# Generated by Django 4.2.2 on 2024-11-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="class_info",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="session_info",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
