# Generated by Django 4.2.2 on 2024-11-10 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("academic", "__first__"),
        ("account", "0002_alter_userprofile_class_info_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="class_info",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="session_info",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.classinfo",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="student_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academic.session",
            ),
        ),
    ]
