# Generated by Django 4.2.5 on 2024-11-19 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('professor', 'Professor'), ('teacher', 'Teacher'), ('register', 'Register'), ('student', 'Student'), ('employee', 'employee')], max_length=15),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='message_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
