# Generated by Django 5.1.4 on 2024-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_userprofile_password_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("professor", "Professor"),
                    ("teacher", "Teacher"),
                    ("register", "Register"),
                    ("student", "Student"),
                    ("employee", "employee"),
                ],
                default="student",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(default="img/man.png", upload_to="admin/"),
        ),
    ]
