# Generated by Django 5.1.4 on 2024-12-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_academicinfo_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=496119, unique=True),
        ),
    ]
