# Generated by Django 5.1.4 on 2024-12-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_academicinfo_registration_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=994458, unique=True),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="stay_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hostel", "Hostel"),
                    ("private room", "Private Room"),
                    ("local", "Local"),
                ],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="traveling_mode",
            field=models.CharField(
                blank=True,
                choices=[("college bus", "College Bus"), ("private", "Private")],
                default=None,
                max_length=50,
                null=True,
            ),
        ),
    ]
