# Generated by Django 5.1.4 on 2024-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_academicinfo_registration_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicinfo",
            name="college_bus_stop",
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=694949, unique=True),
        ),
    ]
