# Generated by Django 5.1.4 on 2024-12-05 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_academicinfo_college_bus_stop_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousacademicinfo",
            name="cet_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="cet_roll_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="eligibility_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="home_university",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_additional_eligibility_subject_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_board_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_chem_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_english_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_math_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_passing_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_phy_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_seat_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_subject_percentage_of_additional",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="hsc_total_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="jee_application_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="jee_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="qualifying_exam_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="ssc_board_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="ssc_maths_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="ssc_passing_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="ssc_seat_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="previousacademicinfo",
            name="ssc_total_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=452762, unique=True),
        ),
        migrations.AlterField(
            model_name="guardianinfo",
            name="father_yearly_income",
            field=models.CharField(max_length=20),
        ),
    ]
