# Generated by Django 5.1.4 on 2024-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_previousacademicinfo_cet_percentage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=238683, unique=True),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")], max_length=10
            ),
        ),
    ]
