# Generated by Django 5.1.4 on 2024-12-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_alter_academicinfo_registration_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicinfo",
            name="registration_no",
            field=models.IntegerField(default=562638, unique=True),
        ),
    ]
